// SPDX-FileCopyrightText: 2026 A.D. (PsychoCoderMonkey) <andrew.dixon@rlyeh.dev>
// SPDX-License-Identifier: GPL-3.0-only

#ifndef RLYEH_AKLO_SCUF_ENVISION_H
#define RLYEH_AKLO_SCUF_ENVISION_H

#include "scuf.h"

#define SCUF_ENVISION_PRO_V2_PRODUCT_ID 0x3a05
#define SCUF_ENVISION_PRO_V2_GAMEPAD_REPORT_ID 0x06

enum scufEnvisionProV2GenericDesktopUsage
{
  SCUF_ENVISION_PRO_V2_USAGE_X = 0x30,
  SCUF_ENVISION_PRO_V2_USAGE_Y = 0x31,
  SCUF_ENVISION_PRO_V2_USAGE_Z = 0x32,
  SCUF_ENVISION_PRO_V2_USAGE_RX = 0x33,
  SCUF_ENVISION_PRO_V2_USAGE_RY = 0x34,
  SCUF_ENVISION_PRO_V2_USAGE_RZ = 0x35,
  SCUF_ENVISION_PRO_V2_USAGE_HAT_SWITCH = 0x39,
};

#define SCUF_ENVISION_PRO_V2_SIGNED_AXIS_MIN (-32768)
#define SCUF_ENVISION_PRO_V2_SIGNED_AXIS_MAX 32767

#define SCUF_ENVISION_PRO_V2_UNSIGNED_AXIS_MIN 0
#define SCUF_ENVISION_PRO_V2_UNSIGNED_AXIS_MAX 1023

#define SCUF_ENVISION_PRO_V2_HAT_SWITCH_MIN 0
#define SCUF_ENVISION_PRO_V2_HAT_SWITCH_MAX 7
#define SCUF_ENVISION_PRO_V2_HAT_SWITCH_HAS_NULL_STATE 1

enum scufEnvisionProV2ButtonUsage
{
  SCUF_ENVISION_PRO_V2_BUTTON_A = 1,
  SCUF_ENVISION_PRO_V2_BUTTON_B = 2,
  SCUF_ENVISION_PRO_V2_BUTTON_X = 3,
  SCUF_ENVISION_PRO_V2_BUTTON_Y = 4,
  SCUF_ENVISION_PRO_V2_BUTTON_LB = 5,
  SCUF_ENVISION_PRO_V2_BUTTON_RB = 6,
  SCUF_ENVISION_PRO_V2_BUTTON_SELECT = 7,
  SCUF_ENVISION_PRO_V2_BUTTON_START = 8,
  SCUF_ENVISION_PRO_V2_BUTTON_L3 = 9,
  SCUF_ENVISION_PRO_V2_BUTTON_R3 = 10,
  SCUF_ENVISION_PRO_V2_BUTTON_GUIDE = 11,
};

#endif /* RLYEH_AKLO_SCUF_ENVISION_H */
